"""
coverage_report.py  – auto-generated by instrument_project.py
Run this after executing your instrumented binary:

    python3 coverage_report.py [coverage.log] [--sort count|name]
"""

import sys
import argparse
from pathlib import Path
from collections import Counter, defaultdict


def load_log(path: str) -> Counter:
    p = Path(path)
    if not p.exists():
        print(f"[ERROR] Log file not found: {path}")
        print("  → Did you run the instrumented binary first?")
        sys.exit(1)
    lines = [l.strip() for l in p.read_text().splitlines() if l.strip()]
    return Counter(lines)


def parse_flag(flag: str) -> tuple[str, str]:
    """Split 'if3_sensor' → ('if3', 'sensor')."""
    parts = flag.rsplit("_", 1)
    return (parts[0], parts[1]) if len(parts) == 2 else (flag, "?")


def print_report(counts: Counter, sort_by: str):
    if not counts:
        print("No coverage data found in log. Was the binary run?")
        return

    # Group by file
    by_file: dict[str, list[tuple[str, int]]] = defaultdict(list)
    for flag, count in counts.items():
        construct, fname = parse_flag(flag)
        by_file[fname].append((flag, count))

    total_flags   = len(counts)
    total_hits    = sum(counts.values())

    print("=" * 60)
    print("  COVERAGE REPORT")
    print("=" * 60)

    for fname in sorted(by_file):
        entries = by_file[fname]
        if sort_by == "count":
            entries.sort(key=lambda x: x[1], reverse=True)
        else:
            entries.sort(key=lambda x: x[0])

        print(f"\n  📄  {fname}")
        print(f"  {'Flag':<30} {'Hits':>6}")
        print(f"  {'-'*30}  {'-'*6}")
        for flag, count in entries:
            bar = "█" * min(count, 20)
            print(f"  {flag:<30} {count:>6}  {bar}")

    print()
    print("=" * 60)
    print(f"  Total unique flags hit : {total_flags}")
    print(f"  Total executions logged: {total_hits}")
    print("=" * 60)


def main():
    ap = argparse.ArgumentParser(description="Display C/C++ coverage report.")
    ap.add_argument("logfile", nargs="?", default="coverage.log",
                    help="Path to coverage.log (default: coverage.log)")
    ap.add_argument("--sort", choices=["name", "count"], default="name",
                    help="Sort flags by name (default) or by hit count")
    args = ap.parse_args()

    counts = load_log(args.logfile)
    print_report(counts, args.sort)


if __name__ == "__main__":
    main()
