"""
instrument_project.py
---------------------
Usage:
    python3 instrument_project.py main.c dep1.c dep2.c ...
    python3 instrument_project.py main.c dep1.c dep2.c --outdir instrumented/
    python3 instrument_project.py main.c dep1.c dep2.c --logfile my_coverage.log

What it does:
    1. Reads every source file.
    2. Runs the Analyser to inject  LOG_FLAG("flagname");  at every
       execution-block boundary.
    3. Prepends  #include "coverage.h"  to each file.
    4. Writes instrumented copies to --outdir  (default: ./instrumented/).
    5. Generates coverage.h  (the LOG_FLAG macro).
    6. Generates coverage_report.py  (aggregates coverage.log after a run).

After instrumenting:
    gcc instrumented/main.c instrumented/dep1.c ... -o my_program
    ./my_program
    python3 coverage_report.py            # pretty-prints coverage.log
"""

import argparse
import shutil
from pathlib import Path

from instrumenter import Analyser


# ---------------------------------------------------------------------------
# coverage.h  – shared header injected into every instrumented file
# ---------------------------------------------------------------------------

COVERAGE_H = '''\
/* coverage.h – auto-generated by instrument_project.py */
#ifndef COVERAGE_H
#define COVERAGE_H

#include <stdio.h>

/*
 * LOG_FLAG(name)
 * Appends one line to coverage.log every time this macro is executed.
 * The Python aggregator counts occurrences to produce hit counts.
 */
#define LOG_FLAG(name) do {                         \\
    FILE *_cov_f = fopen("coverage.log", "a");      \\
    if (_cov_f) {                                   \\
        fprintf(_cov_f, "%s\\n", name);              \\
        fclose(_cov_f);                             \\
    }                                               \\
} while(0)

#endif /* COVERAGE_H */
'''


# ---------------------------------------------------------------------------
# coverage_report.py  – run after the binary to show results
# ---------------------------------------------------------------------------

REPORT_PY = '''\
"""
coverage_report.py  – auto-generated by instrument_project.py
Run this after executing your instrumented binary:

    python3 coverage_report.py [coverage.log] [--sort count|name]
"""

import sys
import argparse
from pathlib import Path
from collections import Counter, defaultdict


def load_log(path: str) -> Counter:
    p = Path(path)
    if not p.exists():
        print(f"[ERROR] Log file not found: {path}")
        print("  → Did you run the instrumented binary first?")
        sys.exit(1)
    lines = [l.strip() for l in p.read_text().splitlines() if l.strip()]
    return Counter(lines)


def parse_flag(flag: str) -> tuple[str, str]:
    """Split 'if3_sensor' → ('if3', 'sensor')."""
    parts = flag.rsplit("_", 1)
    return (parts[0], parts[1]) if len(parts) == 2 else (flag, "?")


def print_report(counts: Counter, sort_by: str):
    if not counts:
        print("No coverage data found in log. Was the binary run?")
        return

    # Group by file
    by_file: dict[str, list[tuple[str, int]]] = defaultdict(list)
    for flag, count in counts.items():
        construct, fname = parse_flag(flag)
        by_file[fname].append((flag, count))

    total_flags   = len(counts)
    total_hits    = sum(counts.values())

    print("=" * 60)
    print("  COVERAGE REPORT")
    print("=" * 60)

    for fname in sorted(by_file):
        entries = by_file[fname]
        if sort_by == "count":
            entries.sort(key=lambda x: x[1], reverse=True)
        else:
            entries.sort(key=lambda x: x[0])

        print(f"\\n  📄  {fname}")
        print(f"  {'Flag':<30} {'Hits':>6}")
        print(f"  {'-'*30}  {'-'*6}")
        for flag, count in entries:
            bar = "█" * min(count, 20)
            print(f"  {flag:<30} {count:>6}  {bar}")

    print()
    print("=" * 60)
    print(f"  Total unique flags hit : {total_flags}")
    print(f"  Total executions logged: {total_hits}")
    print("=" * 60)


def main():
    ap = argparse.ArgumentParser(description="Display C/C++ coverage report.")
    ap.add_argument("logfile", nargs="?", default="coverage.log",
                    help="Path to coverage.log (default: coverage.log)")
    ap.add_argument("--sort", choices=["name", "count"], default="name",
                    help="Sort flags by name (default) or by hit count")
    args = ap.parse_args()

    counts = load_log(args.logfile)
    print_report(counts, args.sort)


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Core instrumentation
# ---------------------------------------------------------------------------

def instrument_file(src_path: Path, out_path: Path):
    """Read, instrument, prepend header include, write instrumented copy."""
    source = src_path.read_text(encoding="utf-8")

    analyser = Analyser(source, file_stem=src_path.stem)
    instrumented = analyser.get_instrumented()

    # Prepend coverage.h include (only if not already there)
    include_line = '#include "coverage.h"\n'
    if include_line not in instrumented:
        instrumented = include_line + instrumented

    out_path.write_text(instrumented, encoding="utf-8")
    flag_count = sum(analyser._counters.values())
    print(f"  ✅  {src_path.name:30s} → {out_path}  ({flag_count} flags injected)")
    return flag_count


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="Instrument C/C++ files for block-level coverage tracking."
    )
    ap.add_argument("sources", nargs="+", metavar="FILE",
                    help="Source files: first is treated as main, rest as dependencies")
    ap.add_argument("--outdir", default="instrumented",
                    help="Output directory (default: instrumented/)")
    ap.add_argument("--logfile", default="coverage.log",
                    help="Runtime log file path baked into coverage.h (default: coverage.log)")

    args = ap.parse_args()
    out_dir = Path(args.outdir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write coverage.h (replace logfile path if custom)
    header_content = COVERAGE_H
    if args.logfile != "coverage.log":
        header_content = header_content.replace('"coverage.log"', f'"{args.logfile}"')
    (out_dir / "coverage.h").write_text(header_content, encoding="utf-8")
    print(f"\n📁  Output directory : {out_dir}/")
    print(f"📝  Log file         : {args.logfile}")
    print(f"\nInstrumenting files:")

    total_flags = 0
    for src in args.sources:
        src_path = Path(src)
        if not src_path.exists():
            print(f"  ❌  {src}  – file not found, skipping")
            continue
        out_path = out_dir / src_path.name
        total_flags += instrument_file(src_path, out_path)

    # Write coverage_report.py next to this script (or in cwd)
    report_path = Path("coverage_report.py")
    report_path.write_text(REPORT_PY, encoding="utf-8")

    print(f"\n🔍  coverage_report.py written to: {report_path.resolve()}")
    print(f"\n{'='*55}")
    print(f"  Total flags injected across all files: {total_flags}")
    print(f"{'='*55}")
    print(f"""
Next steps:
  1. Compile:
       gcc {' '.join(str(out_dir/Path(s).name) for s in args.sources)} -o my_program

  2. Run your binary:
       ./my_program

  3. View terminal coverage:
       python3 coverage_report.py
       python3 coverage_report.py --sort count

  4. Generate visual HTML report:
       python3 html_report.py {' '.join(Path(s).name for s in args.sources)}
       # open coverage_report.html in your browser
""")


if __name__ == "__main__":
    main()
